spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    url: ${APPLICATION_DATASOURCE_URL_DEV}
    username: ${APPLICATION_DATASOURCE_USERNAME}
    password: ${APPLICATION_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver