services:
  yapp-alarm-server:
    image: yapp_alarm
    container_name: yapp-alarm-server
    build:
      context: .
      dockerfile: dockerfile-alarm-dev
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      APPLICATION_DATASOURCE_URL_DEV: jdbc:postgresql://postgresql:5432/yapp?currentSchema=alarm
      APPLICATION_DATASOURCE_USERNAME: yapp
      APPLICATION_DATASOURCE_PASSWORD: yapp
    ports:
      - '8081:8081'
    networks:
      - yapp-network

networks:
  yapp-network:
    external: true