services:
  redis:
    container_name: yapp_redis
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - app-network

  app:
    image: yapp_alarm
    container_name: yapp_alarm_server
    build:
      context: .
      dockerfile: dockerfile-alarm-dev
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - '8081:8081'
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network: