profile:
  active: local

server:
  port: 8081

spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  docker:
    compose:
      enabled: false
      lifecycle-management: start_and_stop
      stop:
        command: down
        timeout: 1m
      file: docker-compose-alarm-local.yml
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true